### ISSUE TITLE
## Medusa user creation

### ISSUE THREAD

**Issue by shavidze** [medusajs/admin#196]
## When I'm trying to create a medusa user by the command line getting the error 
![Screenshot_2](https://user-images.githubusercontent.com/23502763/145840181-4fcce153-442e-457a-a25b-02eaee8c906d.png)

**Comment by srindom** [comment]
This typically happens if you run the `medusa user` command in a folder that is not a Medusa project i.e. a node project with `@medusajs/medusa` in the package.json

Or if you haven't installed the Medusa package. 

So please verify that you are running the command from the root of your Medusa project and that you have run `yarn` or `npm i` :)

**Comment by shavidze** [comment]
I'm just trying to run admin project locally, install @medusajs/medusa globally with npm and I'm running this command from the root of admin project.

**Comment by olivermrbl** [comment]
You need to run the command from root of your Medusa project and not the admin :)

**Comment by shavidze** [comment]
How to login in medusa admin project? is not is possible?

**Comment by srindom** [comment]
https://github.com/medusajs/admin#-quickstart

It may be wort following the steps in the Quickstart to make sure you have a Medusa server up and running :)

**Comment by shavidze** [comment]
> [medusajs/admin#-quickstart](https://github.com/medusajs/admin#-quickstart)
> 
> It may be worth following the steps in the Quickstart to make sure you have a Medusa server up and running :)

Hmm yep, I didn't read it carefully, thanks and sorry.

**Comment by onedawa** [comment]
THis trips up so many newbies, the cli may need to display a more helpful error
