### ISSUE TITLE
Bug: Accordion expand/collapse animation inconsistencies

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#450]
Investigate why the expand/collapse animations are different for different accordion items. 

Specifically the first item collapses and expands, while other items don't collapse and expand, instead they fade in as seen below:

https://user-images.githubusercontent.com/88927411/159734418-6deb2a18-859b-49c0-acbe-7d37789bf70e.mov

**Comment by kasperkristensen** [comment]
The issue seems to stem from the use of the css variable `var(--radix-accordion-content-height);`. For some reason this value only works properly for the first `Item`, and for subsequent `Item`'s the value is unset when the item is open so the animation ends up being `from height 0 -> to height undefined` when opening and `from height undefined -> to height 0` when closing. Will try and investigate it 😄
