### ISSUE TITLE
Can't create draft order without a customer.

### ISSUE THREAD

**Issue by dwene** [medusajs/admin#639]
API is returning 400 error saying that email is required, looks like the Admin is sending an empty string.

Running on the latest version of the develop branch: https://www.loom.com/share/e50997fc20964e18b51150e1e3b9629d

**Comment by olivermrbl** [comment]
The culprit of your issue is, that you do not fill out the "Find or create customer" input field with an email.

I completely understand, why you wouldn't do that since the UX is not super intuitive right now. I'll pass the info along to the design department and let them come up with a revised version.

**Comment by revskill10** [comment]
Got this issue, too, it's unclear what's going wrong though.

**Comment by olivermrbl** [comment]
@revskill10 I believe it's because the following input field is not filled out with an email:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/59018053/179456861-229fa453-67e2-4e89-bb35-0416b71fac9c.png">

Can I get you to retry having filled it out? Again, I've pushed this to design and the plan is to remake the draft order creation flow.

**Comment by revskill10** [comment]
@olivermrbl In my case, i got the issue related to `quantity` is not confirming to the format. It's kinda weird error.
