### ISSUE TITLE
Unhandled runtime Error in function _callee$ in ./src/utils/consolidate-images.ts:8

### ISSUE THREAD

**Issue by WizzDex** [medusajs/admin#672]
I can't upload images, I've tried using "await" but still no luck

No images work, regardless of the extension. Using Node.js V16.16, Medusa Next.JS starter.
![image](https://user-images.githubusercontent.com/50861043/184537852-8b9cdc30-0606-4b2e-a9d3-e5d723267164.png)
![image](https://user-images.githubusercontent.com/50861043/184537907-8e279798-9112-401c-b064-ab9c7498ff29.png)

**Comment by kasperkristensen** [comment]
Hi @WizzDex, did you install a file service plugin to your Medusa server that handles image uploads?

**Comment by WizzDex** [comment]
> Hi @WizzDex, did you install a file service plugin to your Medusa server that handles image uploads?

Nope, where do I get one?

**Comment by WizzDex** [comment]
and how do I implement it into Medusa? My bad, I'm new, been using shopify and decided to switch to Medusa.

**Comment by kasperkristensen** [comment]
We have three official plugins that you can choose from, heres the docs for our MinIO plugin – https://docs.medusajs.com/add-plugins/minio. We also have a S3 and Spaces plugin, you can find the docs for those in the sidebar of the previous link. There are also other alternatives maintained by the community, you can find a list of those here – https://github.com/adrien2p/awesome-medusajs#plugins. Hope that helps and otherwise let me know, I'll close this issue for now 😄

**Comment by WizzDex** [comment]
Hey! Thanks for getting back to me, I got Minio setup but when it tries to send the data to the bucket it gives me this error
![image](https://user-images.githubusercontent.com/50861043/184661935-f4986d40-4a0e-442c-997e-4667415bd757.png)
Yes, the Minio bucket name, access-key, secret access key are all correct

**Comment by WizzDex** [comment]
I've managed to make it work by changing the "MINIO_ENDPOINT" .env from "192.168.0.119:9001" to http://192.168.0.119:9001", It works now, it uploads files to the bucket but I get this error instead
![image](https://user-images.githubusercontent.com/50861043/184667802-0bf6d039-a8ef-4b2d-b46c-561397fc8f2f.png)
The bucket does receive images, as of right now it says about 1MB is used on the bucket but the product is not listed. File types used: JPG, PNG none work
