### ISSUE TITLE
Quickstart Installation error - Module not found Error

### ISSUE THREAD

**Issue by patrick-kw-chiu** [medusajs/admin#761]
Hello all!

First of all, thank you for building such a comprehensive open-source Shopify alternative!
I am trying to follow the [quickstart](https://docs.medusajs.com/admin/quickstart/) guide. However, when I try to `npm run start`, it throws the following "module not found"  errors

```
Can't resolve '@gatsbyjs/reach-router/lib/utils' in '/medusa-trial/admin-portal/.cache'
Can't resolve 'gatsby-link' in '/medusa-trial/admin-portal/.cache'
Can't resolve 'gatsby-react-router-scroll' in '/medusa-trial/admin-portal/.cache'
Can't resolve 'gatsby-script' in '/medusa-trial/admin-portal/.cache'
```

Wondering if anyone knows why? Thanks in advanced!

### Here are more information...
OS: Mac
Node version: 16.13.0

### Steps to reproduce:
git clone https://github.com/medusajs/admin medusa-admin
cd medusa-admin
npm install
npm run start

**Comment by kasperkristensen** [comment]
Hi @patrick-kw-chiu 

Hard to say why you are getting this error, but here is what I would try:

1. Clear the Gatsby cache with `gatsby clean`
2. Delete your `node_modules` folder, and re-install the dependencies.

If the error persists after this, I recommend you try to use `yarn` instead of `npm`. 

Let me know if it works out for you.

**Comment by patrick-kw-chiu** [comment]
Thank for so much. It works!
