### ISSUE TITLE
Reloads to same login page after successfull login when using different domains.

### ISSUE THREAD

**Issue by anand-010** [medusajs/admin#801]
I have hosted medusa admin on netlify and medusa server on digital occean with nginx ssl certificates.
I've added ADMIN_CORS to the medusa server and it worked.
When i entered right email and password the page reloads to the same login page again.
when i enter wrong email and pass i got the error messages.
what went wrong here.
Do i configured anyting wrong here.
I have successfully logged in when i installed both on local machines.

**Comment by kasperkristensen** [comment]
There can be two issues here:
 
1. You have disabled cross-site cookies in your browser or system settings. This is the default when using Safari. Because you have your server on www.domain-a.com and your admin on www.domain-b.com, then the session cookie won't be saved. 
2. One or both of your domains are on the public suffix list, this is for example if your admin has a domain that includes `.netlify.app` or your server is on `*.heroku.app` etc.

**Comment by anand-010** [comment]
Thank you.
It at least worked on mozilla firefox it's enough for admin pages.
