### ISSUE TITLE
[Bug] Creating second product with exactly same handle throws an enigmatic error

### ISSUE THREAD

**Issue by mateuszkula** [medusajs/admin#819]
While trying to create a product with the same title twice(and not creating  custom handle) or creating two products with different titles but the same `handle` value causes error on admin panel side with very enigmatic error message for the end user:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/30259869/204490779-87820677-3fa9-4e32-9ce7-56028221c50d.png">

Under-the-hood backend fails on sql insert but no meaningful message is sent back to UI:
```error:   SQLITE_CONSTRAINT: UNIQUE constraint failed: product.handle
QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: product.handle
```

**Comment by kasperkristensen** [comment]
Hi @mateuszkula, if you use Postgres it will actually throw the correct error from the server.

We don't handle all SQLite errors super gracefully, since it is not meant to be used in a real setting, as described in our docs. Since it is not meant to be used for anything other than quickly doing a bit of exploration of Medusa, I am not sure it would be something we are going to handle better moving forward. But in any case this issue should be opened against the core repo, and not the admin, as we handle error descriptions on the backend :)
