### ISSUE TITLE
[Bug] Could not resolve "@textea/dev-kit/utils"

### ISSUE THREAD

**Issue by lorenzolaricchia** [medusajs/admin#847]
On `yarn start`

`[ERROR] Could not resolve "@textea/dev-kit/utils"`
```
 node_modules/@textea/json-viewer/dist/index.js:3:314:
      3 │ ...erial'), require('zustand'), require('zustand/context'), require('zustand/middleware'), require('copy-to-clipboard'), require('@textea/dev-kit/utils'), require('group-items')) :
        ╵                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~
```

I think the error is related to `@textea/json-viewer`.

**Comment by DGLcsGaming** [comment]
I'm having the same issue from a fresh install!

**Comment by DGLcsGaming** [comment]
I resolved this by replacing `"@textea/json-viewer": "2.12.1"` to `"@textea/json-viewer": "2.12.0"` in `package.json` file, and then running `npm install`

**Comment by csu6** [comment]
Hello,
I have the same issue, and solved by using this command line: npm ci
and after this you can run the project with npm start

**Comment by olivermrbl** [comment]
Thanks for reporting this issue. It seems updating the dependency resolves the issue. We'll attend to it!

cc @kasperkristensen

**Comment by lorenzolaricchia** [comment]
> I resolved this by replacing `"@textea/json-viewer": "2.12.1"` to `"@textea/json-viewer": "2.12.0"` in `package.json` file, and then running `npm install`

This didn't work for me. I am using `yarn`. Maybe I should use `npm`?

**Comment by kasperkristensen** [comment]
I don't think that we can resolve the issue by changing the version looking into their code, it seems like every version is affected by the bundled code depending on a devDependency which obviously isn't part of the final bundle. Your package manager should be able to resolve this by itself, mine does at least (tested with both yarn and npm), but depending on your version of npm/yarn that might not be the case.

@olivermrbl  A quick here-and-now fix would be to explicitly add `@textea/dev-kit` as a dependency, and then start working on creating our own json viewer component. We added it as a temporary fix because the previous package we were using was not compatible with React >= 17, and this particular package has a pretty hefty bundle size that I think is a bit outrageous for our use case at least.
I am going to search around a bit and see if I can find a substitute that we can use instead as that would be the best case. I'll open a hotfix later where I either swap out the dependency or apply the dirty quick fix solution until we can implement our own.

**Comment by lorenzolaricchia** [comment]
Why does `@textea/json-viewer` creates building problems in the project created through `yarn create medusa-app`, but does not affect the project created cloning directly medusa admin (`https://github.com/medusajs/admin`).

**Comment by abdrmlr** [comment]
> Why does `@textea/json-viewer` creates building problems in the project created through `yarn create medusa-app`, but does not affect the project created cloning directly medusa admin (`https://github.com/medusajs/admin`) ?

Yes, direct clone from medusa admin contains latest fixes at (https://github.com/medusajs/admin) works flawlessly now, Thanks Medusa Team
