### ISSUE TITLE
[Question] Is `yarn.lock` needed here?

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#860]
Can we exclude `yarn.lock` from being committed into this repository?

I use npm and can't have both package-lock.json and yarn.lock in the project since it messes with dokku deploys: <https://help.heroku.com/0KU2EM53/why-is-my-node-js-build-failing-because-of-conflicting-lock-files>

I have it deleted and it's always the only merge conflict when pulling admin.
As far as I know it shouldn't be commited here anyway.

**Comment by kasperkristensen** [comment]
We do need it in this project in order for us to ensure that the team and contributors have the exact same versions of dependencies. That is why you should commit the `.lock` file in projects like this. I do realize it's pretty annoying to deal with, and it is one of the many reasons why we are working on shipping admin as a server plugin, since we don't want users to have to deal with this, installing `devDepenedencies`, etc, unless they are looking to contribute to the project or are doing heavy customization.
