### ISSUE TITLE
On slow network, `hi index` message is displayed if the orders page takes time to load

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#873]
The issue reported previously is still generating https://github.com/medusajs/admin/issues/643

**Comment by kasperkristensen** [comment]
Hi @ymaheshwari1, you need to update your admin version, as it is no longer the case for the newest version 🙂 If you have updated your admin project and it still shows then it is most likely because you haven't handled potential merge conflicts correctly resulting in old files still being in your project.
