### ISSUE TITLE
`tsc`, `eslint`, and `vitest` exit with errors

### ISSUE THREAD

**Issue by dmitana** [medusajs/admin#920]
Hello, Medusa team and contributors!

First of all, thank you for this Medusa Admin interface.

I tried creating an admin app both ways, by [Medusa Admin Quickstart](https://docs.medusajs.com/admin/quickstart) and [Install Medusa with create-medusa-app](https://docs.medusajs.com/create-medusa-app) respectively. In both cases, running `tsc`, `eslint`, and `vitest` exited with errors. I didn't change any of the populated files.

I ran those commands in the following way:
* `tsc` using `npm run check` results in `Found 485 errors in 193 files.`,
* `eslint` using  `npx eslint --max-warnings 0 . --ext .ts,.js,.tsx,.jsx` results in `19692 problems (19019 errors, 673 warnings)`,
* `vitest` using `npm run test` results in 
```
 Test Files  2 failed | 7 passed (9)
      Tests  2 failed | 22 passed (24)
   Start at  21:59:16
   Duration  7.56s (transform 713ms, setup 1.92s, collect 8.30s, tests 2.96s)
```

Please, is this a normal state or am I doing something wrong?

**Comment by kasperkristensen** [comment]
Hi @dmitana 

You aren’t supposed to run `tsc` to build admin, you should use `vite build`. There are a lot of TS warnings in the project mainly due to types from Medusa changing over time and updates to the version of TS, without making the necessary changes to make TS “happy”. It doesn’t mean that the code doesn’t work, just that the types are slightly off. 

This repo is not being worked on anymore as we are deprecating it in favor of shipping admin as a `npm` package. All of the eslint warnings and test errors have been fixed over in the new repo, we might make a final push over here to clean up the project for people that are not ready to migrate to the new plugin once is shipped in two weeks time.

closing this as it is the “expected” behavior. If you have any issues getting the admin up and running feel free to ask more questions 🙂
